INSERT INTO role (name,permits) VALUES ('USER','ROLE_USER');
INSERT INTO role (name,permits) VALUES ('ADMINISTRATOR','ROLE_ADMIN');
INSERT INTO user (first_name, last_name, user_name, password, identification, id_role) VALUES ('user', 'Garzon', 'user', '$2a$10$O9wxmH/AeyZZzIS09Wp8YOEMvFnbRVJ8B4dmAMVSGloR62lj.yqXG',100, 1);
INSERT INTO user (first_name, last_name, user_name, password, identification, id_role) VALUES ('admin', 'Bohorquez', 'admin', '$2a$10$DOMDxjYyfZ/e7RcBfUpzqeaCs8pLgcizuiQWXPkU35nOhZlFcE9MS',101, 2);
INSERT INTO schedule (day,start_time,end_time) VALUES ('Lunes',8,18);
INSERT INTO schedule (day,start_time,end_time) VALUES ('Martes',8,18);
INSERT INTO schedule (day,start_time,end_time) VALUES ('Miercoles',8,18);
INSERT INTO schedule (day,start_time,end_time) VALUES ('Jueves',8,18);
INSERT INTO schedule (day,start_time,end_time) VALUES ('Vienes',8,18);
INSERT INTO schedule (day,start_time,end_time) VALUES ('Sabado',8,18);
INSERT INTO schedule (day,start_time,end_time) VALUES ('Domingo',8,18);
INSERT INTO service (name,description,path_img,state) VALUES ('Labado','labado de motro','algun path para la img',true);
INSERT INTO service (name,description,path_img,state) VALUES ('mecanica','de motro','algun path para la img',true);
INSERT INTO booking (id_user,id_service,day,start_time) VALUES(1,1,{ts '2020-12-15 00:00:00.00'},8);
INSERT INTO booking (id_user,id_service,day,start_time) VALUES(1,1,{ts '2020-12-15 00:00:00.00'},9);
INSERT INTO booking (id_user,id_service,day,start_time) VALUES(1,1,{ts '2020-12-15 00:00:00.00'},10);
INSERT INTO payment (type,description) VALUES ('TDC','Tarjeta de credito');
INSERT INTO payment (type,description) VALUES ('PSE','Cuenta corriente');
INSERT INTO payment (type,description) VALUES ('EFE','Efectivo');
INSERT INTO billing (id_booking,id_payment,description,date,start_time,amount,state) VALUES (1,1,'pago de factura',{ts '2020-12-15 00:00:00.00'},8,300000,false);
